server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ushom?Unicode=true&characterEncoding=utf8
    username: root
    password: zhang11110717
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
mybatis_config_file: mybatis-config.xml
mybatis.type-aliases-package: com.zxr.mygraduation.entity
mybatis.mapper-locations: classpath:mapper/**.xml



  